include: package:lint/analysis_options.yaml


linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    parameter_assignments: true
    sort_pub_dependencies: false


analyzer:
  errors:
    missing_required_param: error
    avoid_classes_with_only_static_members: error
    sort_constructors_first: error
    parameter_assignments: error